name: Redshift Keshav 2
fullyQualifiedName: Redshift Keshav 2
serviceType: Redshift
description: <p>new desc</p>
connection:
  config:
    type: Redshift
    scheme: redshift+psycopg2
    sslMode: disable
    authType:
      password: fernet:gAAAAABpqiY6tmcm0E1zOcgW5Dky-W-aCPnheBBCjXAEcmFKx4K2pb0T6M4oHZhogi-DMc-GmKXSb9EZ4PTC7RNFYNzDEWt3whAjca3A-Rj_FwkDtwhjtBkKnzH_siOOgscBDGZWEN1ZlaZqkiSqZ-JmBHbMvANiRw==
    database: aaa
    hostPort: aaa
    username: keshav.mohta@getcollate.io
    supportsDataDiff: true
    supportsDatabase: true
    supportsProfiler: true
    ingestAllDatabases: false
    tableFilterPattern:
      excludes: []
      includes: []
    schemaFilterPattern:
      excludes:
        - ^information_schema$
      includes: []
    supportsQueryComment: true
    databaseFilterPattern:
      excludes:
        - ^template1$
      includes: []
    supportsDBTExtraction: true
    supportsSystemProfile: false
    sampleDataStorageConfig:
      config:
        prefix: ""
        bucketName: ""
        overwriteData: true
        storageConfig:
          assumeRoleSessionName: OpenMetadataSession
        filePathPattern: "{service_name}/{database_name}/{database_schema_name}/{table_name}/sample_data.parquet"
    supportsUsageExtraction: true
    supportsLineageExtraction: true
    supportsMetadataExtraction: true
    supportsIncrementalMetadataExtraction: true
pipelines:
  - id: 95b5a3a6-5992-41ff-8508-8813b2829912
    type: ingestionPipeline
    name: b46ce904-63cf-4142-ac81-43f141b1356b
    fullyQualifiedName: Redshift Keshav 2.b46ce904-63cf-4142-ac81-43f141b1356b
    displayName: Metadata Agent
    deleted: false
tags: []
owners:
  - id: 78260c88-265f-4d4a-8bd7-391b42ed207c
    type: user
    name: keshav.mohta
    fullyQualifiedName: '"keshav.mohta"'
    description: ""
    displayName: Keshav Mohta
    deleted: false
incrementalChangeDescription:
  fieldsAdded: []
  fieldsUpdated:
    - name: description
      oldValue: ""
      newValue: <p>new desc</p>
  fieldsDeleted: []
  previousVersion: 0.1
  changeSummary: {}
entityStatus: Unprocessed
dataProducts: []
ingestionRunner:
  id: 97327a7f-0fba-4ab8-bf19-431f6d44ff36
  type: ingestionRunner
